name: Build & Test CI


on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies 
        run: yarn install

      - name: Build pacakges
        run: yarn build

      - name: Automated tests
        run: yarn test
